services:
  - type: web
    name: site-livro
    repo: "REPLACE_WITH_YOUR_REPO_URL"
    env: node
    plan: free
    buildCommand: "npm ci && npx prisma generate && npm run build"
    startCommand: "npx prisma migrate deploy && npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
